App:
  LogSavePath: storage/logger
  LogFileName: app
  LogFileExt: .log
  DefaultContextTimeout: 30

Proxy:
  ProxyItems:
    -
      Name: kuwo
      Cookie: Hm_lvt_cdb524f42f0ce19b169a8071123a4797=1623339177,1623339183; _ga=GA1.2.1195980605.1579367081; Hm_lpvt_cdb524f42f0ce19b169a8071123a4797=1623339982; kw_token=3E7JFQ7MRPL; _gid=GA1.2.747985028.1623339179; _gat=1
      CSRF: 3E7JFQ7MRPL
      Host: www.kuwo.cn
      Referer: http://www.kuwo.cn/
      UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
    -
      Name: netease
      # ProxyAddr: http://netease_music_api:3000
      ProxyAddr: http://127.0.0.1:3000


Server:
#  RunMode: debug
  RunMode: release
  HttpPort: 8080
  ReadTimeout: 30
  WriteTimeout: 30