package music

import "github.com/Mistsink/kuwo-api/internal/core/kuwo"

// Generated by https://quicktype.io

type LyricResp struct {
	kuwo.CommonRes
	Data LyricData `json:"data" yzh:"result"`
}

type LyricData struct {
	Lrclist  []Lrclist `json:"lrclist" yzh:"lyric_list"`
	Simpl    Simpl     `json:"simpl"`
	Songinfo Songinfo  `json:"songinfo"`
}

type Lrclist struct {
	LineLyric string `json:"lineLyric" yzh:"lrc_line"`
	Time      string `json:"time" yzh:"lrc_time"`
}

type Simpl struct {
	Musiclist []Songinfo          `json:"musiclist"`
	Playlist  []map[string]string `json:"playlist"`
}

type Songinfo struct {
	Album           string       `json:"album"`
	AlbumID         string       `json:"albumId"`
	Artist          string       `json:"artist"`
	ArtistID        string       `json:"artistId"`
	ContentType     string       `json:"contentType"`
	CoopFormats     []CoopFormat `json:"coopFormats"`
	CopyRight       string       `json:"copyRight"`
	Duration        string       `json:"duration"`
	Formats         string       `json:"formats"`
	HasEcho         interface{}  `json:"hasEcho"`
	HasMv           string       `json:"hasMv"`
	ID              string       `json:"id"`
	IsEXT           interface{}  `json:"isExt"`
	IsNew           interface{}  `json:"isNew"`
	IsPoint         string       `json:"isPoint"`
	Isbatch         interface{}  `json:"isbatch"`
	Isdownload      string       `json:"isdownload"`
	Isstar          string       `json:"isstar"`
	MkvNsig1        string       `json:"mkvNsig1"`
	MkvNsig2        string       `json:"mkvNsig2"`
	MkvRid          string       `json:"mkvRid"`
	Mp3Nsig1        string       `json:"mp3Nsig1"`
	Mp3Nsig2        string       `json:"mp3Nsig2"`
	Mp3Rid          string       `json:"mp3Rid"`
	Mp3Size         string       `json:"mp3Size"`
	Mp4Sig1         string       `json:"mp4sig1"`
	Mp4Sig2         string       `json:"mp4sig2"`
	MusicrID        string       `json:"musicrId"`
	MutiVer         string       `json:"mutiVer"`
	Mvpayinfo       interface{}  `json:"mvpayinfo"`
	Mvpic           interface{}  `json:"mvpic"`
	Nsig1           string       `json:"nsig1"`
	Nsig2           string       `json:"nsig2"`
	Online          string       `json:"online"`
	Params          string       `json:"params"`
	Pay             string       `json:"pay"`
	Pic             string       `json:"pic"`
	PlayCnt         string       `json:"playCnt"`
	RankChange      interface{}  `json:"rankChange"`
	Reason          interface{}  `json:"reason"`
	Score           interface{}  `json:"score"`
	Score100        string       `json:"score100"`
	SongName        string       `json:"songName"`
	SongTimeMinutes string       `json:"songTimeMinutes"`
	Tpay            interface{}  `json:"tpay"`
	Trend           interface{}  `json:"trend"`
	UpTime          string       `json:"upTime"`
	Uploader        string       `json:"uploader"`
}

type CoopFormat string

const (
	The128Kmp3 CoopFormat = "128kmp3"
	The192Kmp3 CoopFormat = "192kmp3"
	The320Kmp3 CoopFormat = "320kmp3"
)
